{% set name = "autopxd2" %}
{% set version = "2.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autopxd2-{{ version }}.tar.gz
  sha256: 8b9d319d1267d7b236393987c3fb5d83b6c69c2bdd3bb7153a93da4f795db7df

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - autopxd = autopxd:cli

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - pycparser
    - python >=3.6

test:
  imports:
    - autopxd
  commands:
    - pip check
    - autopxd --help
  requires:
    - pip

about:
  home: https://github.com/gabrieldemarmiesse/python-autopxd2
  summary: Automatically generate Cython pxd files from C headers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jakirkham
