{% set name = "autopxd2" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autopxd2-{{ version }}.tar.gz
  sha256: 56e6d1af6f2c8b6d8b51fa4a86897f3076760692a05585f673887de2d49b942c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - autopxd = autopxd:cli

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - pycparser
    - python >=3.6

test:
  imports:
    - autopxd
  commands:
    - pip check
    - autopxd --help
  requires:
    - pip

about:
  home: https://github.com/gabrieldemarmiesse/python-autopxd2
  summary: Automatically generate Cython pxd files from C headers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jakirkham
