{% set name = "autopxd2" %}
{% set version = "3.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/autopxd2-{{ version }}.tar.gz
  sha256: d18e8a14dea4c1030d7a1f3a1eef860df3e2c7f97315c5672c944e1b378823bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - autopxd = autopxd:cli

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click
    - pycparser
    - python >=3.7

test:
  imports:
    - autopxd
  commands:
    - pip check
    - autopxd --help
  requires:
    - pip

about:
  home: https://github.com/gabrieldemarmiesse/python-autopxd2
  summary: Automatically generate Cython pxd files from C headers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jakirkham
